spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/lugar_marcado
spring.datasource.username=lugar
spring.datasource.password=lugar123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always